### ISSUE TITLE
visualizing the results

### ISSUE THREAD

**Issue by pull-ups** [HumanoidAgents/HumanoidAgents#2]
Hi, I'm sngwon, and I'm very impressed your implementation for agent world. I want to extend your work for other kind of NPCs, but I realized this repo does not have sources for visualizing results after running all of the codes. Like your WebGL visualization implementation, I want to use such templates and modify some of them. Is it possible for you for sharing web visualization code? 

Thanks.
Sngwon

**Comment by Zhilin123** [comment]
As replied in email some time ago, we are still in the process of improving the WebGL visualization implementation to make it more customizable to various settings, which is taking longer than we initially expected
